services:
  agroveterinaria-gross-web-tobias:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agroveterinaria-gross-web-tobias
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 3000
      TZ: ${GENERIC_TIMEZONE:-America/Argentina/Buenos_Aires}
      NEXT_TELEMETRY_DISABLED: 1

    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:3000 >/dev/null || exit 1"]
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 40s

    networks:
      - proxy
      - db

    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy

      - traefik.http.routers.agroveterinaria-gross-tobias.rule=Host(`agroveterinariagross-tobias.${DOMAIN_NAME:-zubuagency.com}`)
      - traefik.http.routers.agroveterinaria-gross-tobias.entrypoints=websecure
      - traefik.http.routers.agroveterinaria-gross-tobias.tls=true
      - traefik.http.routers.agroveterinaria-gross-tobias.tls.certresolver=mytlschallenge
      - traefik.http.routers.agroveterinaria-gross-tobias.priority=10

      - traefik.http.services.agroveterinaria-gross-tobias.loadbalancer.server.port=3000

networks:
  proxy:
    external: true
  db:
    external: true
    name: ${DB_NETWORK:-n8n_default}