// Mock data for Agroveterinaria Gross

export const clientes = [
  {
    id: 1,
    nombre: "María García",
    telefono: "(376) 456 7890",
    whatsapp: "5493764567890",
    direccion: "Av. Corrientes 1234, CABA",
    email: "maria.garcia@email.com",
    mascotas: [1],
    observaciones: "Cliente frecuente",
    consentimientoWhatsApp: true,
  },
  {
    id: 2,
    nombre: "Carlos López",
    telefono: "(376) 234 5678",
    whatsapp: "5493762345678",
    direccion: "Calle Falsa 123, CABA",
    email: "carlos.lopez@email.com",
    mascotas: [2],
    observaciones: "",
    consentimientoWhatsApp: true,
  },
  {
    id: 3,
    nombre: "Ana Martínez",
    telefono: "(376) 987 6543",
    whatsapp: "5493769876543",
    direccion: "Av. Santa Fe 4567, CABA",
    email: "ana.martinez@email.com",
    mascotas: [3],
    observaciones: "Preferencia horario mañana",
    consentimientoWhatsApp: true,
  },
  {
    id: 4,
    nombre: "Juan Rodríguez",
    telefono: "(376) 555 1234",
    whatsapp: "5493765551234",
    direccion: "Belgrano 890, CABA",
    email: "juan.rodriguez@email.com",
    mascotas: [4, 5],
    observaciones: "",
    consentimientoWhatsApp: false,
  },
  {
    id: 5,
    nombre: "Laura Fernández",
    telefono: "(376) 333 9999",
    whatsapp: "5493763339999",
    direccion: "Rivadavia 2345, CABA",
    email: "laura.fernandez@email.com",
    mascotas: [6],
    observaciones: "Trabaja en el barrio",
    consentimientoWhatsApp: true,
  },
]

export const mascotas = [
  {
    id: 1,
    nombre: "Luna",
    especie: "Perro",
    raza: "Golden Retriever",
    animalTypeId: "perro",
    breedId: "golden-retriever",
    lifeStage: "adult",
    fechaNacimiento: "2021-03-15",
    edad: "3 años",
    sexo: "Hembra",
    peso: "28.5",
    color: "Dorado",
    clienteId: 1,
    dueno: "María García",
    estadoGeneral: "Saludable",
    chip: "985141234567890",
    esterilizado: true,
    alergias: ["Pollo"],
    antecedentes: "Displasia de cadera leve",
    ultimaConsulta: "2024-01-10",
    ultimoDiagnostico: "Control de rutina",
    foto: null,
  },
  {
    id: 2,
    nombre: "Simón",
    especie: "Gato",
    raza: "Siamés",
    fechaNacimiento: "2020-08-22",
    animalTypeId: "gato",
    breedId: "siames",
    lifeStage: "adult",
    edad: "4 años",
    sexo: "Macho",
    peso: "4.2",
    color: "Seal point",
    clienteId: 2,
    dueno: "Carlos López",
    estadoGeneral: "En tratamiento",
    chip: "985141234567891",
    esterilizado: true,
    alergias: [],
    antecedentes: "Enfermedad renal crónica estadío 2",
    ultimaConsulta: "2024-01-12",
    ultimoDiagnostico: "Control ERC",
    foto: null,
  },
  {
    id: 3,
    nombre: "Rocky",
    especie: "Perro",
    raza: "Bulldog Francés",
    fechaNacimiento: "2022-01-10",
    animalTypeId: "perro",
    breedId: "bulldog-frances",
    lifeStage: "adult",
    edad: "2 años",
    sexo: "Macho",
    peso: "12.8",
    color: "Atigrado",
    clienteId: 3,
    dueno: "Ana Martínez",
    estadoGeneral: "Vacuna vencida",
    chip: "985141234567892",
    esterilizado: false,
    alergias: ["Penicilina"],
    antecedentes: "",
    ultimaConsulta: "2023-12-05",
    ultimoDiagnostico: "Dermatitis alérgica",
    foto: null,
  },
  {
    id: 4,
    nombre: "Milo",
    especie: "Perro",
    raza: "Beagle",
    fechaNacimiento: "2019-05-30",
    animalTypeId: "perro",
    breedId: "beagle",
    lifeStage: "adult",
    edad: "5 años",
    sexo: "Macho",
    peso: "14.0",
    color: "Tricolor",
    clienteId: 4,
    dueno: "Juan Rodríguez",
    estadoGeneral: "Control pendiente",
    chip: "985141234567893",
    esterilizado: true,
    alergias: [],
    antecedentes: "Otitis recurrente",
    ultimaConsulta: "2024-01-08",
    ultimoDiagnostico: "Otitis externa",
    foto: null,
  },
  {
    id: 5,
    nombre: "Nina",
    especie: "Gato",
    raza: "Persa",
    fechaNacimiento: "2021-11-15",
    animalTypeId: "gato",
    breedId: "persa",
    lifeStage: "adult",
    edad: "2 años",
    sexo: "Hembra",
    peso: "3.8",
    color: "Blanco",
    clienteId: 4,
    dueno: "Juan Rodríguez",
    estadoGeneral: "Saludable",
    chip: "985141234567894",
    esterilizado: true,
    alergias: [],
    antecedentes: "",
    ultimaConsulta: "2024-01-05",
    ultimoDiagnostico: "Vacunación anual",
    foto: null,
  },
  {
    id: 6,
    nombre: "Max",
    especie: "Perro",
    raza: "Pastor Alemán",
    fechaNacimiento: "2018-07-20",
    animalTypeId: "perro",
    breedId: "pastor-aleman",
    lifeStage: "adult",
    edad: "6 años",
    sexo: "Macho",
    peso: "35.0",
    color: "Negro y fuego",
    clienteId: 5,
    dueno: "Laura Fernández",
    estadoGeneral: "Cirugía programada",
    chip: "985141234567895",
    esterilizado: false,
    alergias: [],
    antecedentes: "Artrosis lumbar",
    ultimaConsulta: "2024-01-11",
    ultimoDiagnostico: "Tumor cutáneo - programar extirpación",
    foto: null,
  },
]

export const turnosHoy = [
  {
    id: 1,
    hora: "09:00",
    mascota: "Luna",
    mascotaId: 1,
    dueno: "María García",
    motivo: "Control postratamiento",
    profesional: "Dr. García",
    estado: "Finalizado",
  },
  {
    id: 2,
    hora: "10:30",
    mascota: "Rocky",
    mascotaId: 3,
    dueno: "Ana Martínez",
    motivo: "Vacunación antirrábica",
    profesional: "Dra. López",
    estado: "En atención",
  },
  {
    id: 3,
    hora: "11:30",
    mascota: "Milo",
    mascotaId: 4,
    dueno: "Juan Rodríguez",
    motivo: "Control otitis",
    profesional: "Dr. García",
    estado: "En espera",
  },
  {
    id: 4,
    hora: "12:00",
    mascota: "Simón",
    mascotaId: 2,
    dueno: "Carlos López",
    motivo: "Control ERC + análisis",
    profesional: "Dra. López",
    estado: "Confirmado",
  },
  {
    id: 5,
    hora: "15:00",
    mascota: "Nina",
    mascotaId: 5,
    dueno: "Juan Rodríguez",
    motivo: "Desparasitación",
    profesional: "Dr. García",
    estado: "Pendiente",
  },
  {
    id: 6,
    hora: "16:30",
    mascota: "Max",
    mascotaId: 6,
    dueno: "Laura Fernández",
    motivo: "Evaluación prequirúrgica",
    profesional: "Dr. García",
    estado: "Confirmado",
  },
]

export const vacunasPendientes = [
  {
    id: 1,
    mascota: "Rocky",
    mascotaId: 3,
    dueno: "Ana Martínez",
    vacuna: "Antirrábica",
    fechaVencimiento: "2024-01-05",
    estado: "Vencida",
    diasVencida: 10,
  },
  {
    id: 2,
    mascota: "Milo",
    mascotaId: 4,
    dueno: "Juan Rodríguez",
    vacuna: "Séxtuple",
    fechaVencimiento: "2024-01-20",
    estado: "Próxima",
    diasRestantes: 5,
  },
  {
    id: 3,
    mascota: "Max",
    mascotaId: 6,
    dueno: "Laura Fernández",
    vacuna: "Antirrábica",
    fechaVencimiento: "2024-01-25",
    estado: "Próxima",
    diasRestantes: 10,
  },
]

export const controlesPendientes = [
  {
    id: 1,
    mascota: "Simón",
    mascotaId: 2,
    dueno: "Carlos López",
    tipo: "Control ERC",
    fechaSugerida: "2024-01-15",
    profesional: "Dra. López",
    prioridad: "Alta",
  },
  {
    id: 2,
    mascota: "Milo",
    mascotaId: 4,
    dueno: "Juan Rodríguez",
    tipo: "Control otitis",
    fechaSugerida: "2024-01-18",
    profesional: "Dr. García",
    prioridad: "Media",
  },
  {
    id: 3,
    mascota: "Luna",
    mascotaId: 1,
    dueno: "María García",
    tipo: "Control displasia",
    fechaSugerida: "2024-02-10",
    profesional: "Dr. García",
    prioridad: "Baja",
  },
]

export const cirugiasProgramadas = [
  {
    id: 1,
    mascota: "Max",
    mascotaId: 6,
    dueno: "Laura Fernández",
    tipo: "Extirpación tumor cutáneo",
    fecha: "2024-01-18",
    hora: "10:00",
    veterinario: "Dr. García",
    estado: "Programada",
  },
  {
    id: 2,
    mascota: "Rocky",
    mascotaId: 3,
    dueno: "Ana Martínez",
    tipo: "Castración",
    fecha: "2024-01-22",
    hora: "09:00",
    veterinario: "Dra. López",
    estado: "Pendiente confirmación",
  },
]

export const estudiosPendientes = [
  {
    id: 1,
    mascota: "Simón",
    mascotaId: 2,
    dueno: "Carlos López",
    tipo: "Análisis de sangre - Perfil renal",
    fechaSolicitud: "2024-01-12",
    estado: "Pendiente de resultado",
  },
  {
    id: 2,
    mascota: "Max",
    mascotaId: 6,
    dueno: "Laura Fernández",
    tipo: "Radiografía de tórax",
    fechaSolicitud: "2024-01-11",
    estado: "Resultado recibido",
  },
  {
    id: 3,
    mascota: "Luna",
    mascotaId: 1,
    dueno: "María García",
    tipo: "Ecografía abdominal",
    fechaSolicitud: "2024-01-10",
    estado: "Informado al dueño",
  },
]

export const recordatoriosProgramados = [
  {
    id: 1,
    destinatario: "Ana Martínez",
    mascota: "Rocky",
    tipo: "Vacuna vencida",
    fechaProgramada: "2024-01-15",
    estado: "Programado",
    mensaje: "Hola, te recordamos que a Rocky le corresponde su vacuna antirrábica que está vencida. Si querés, podés responder este mensaje para coordinar un turno.",
  },
  {
    id: 2,
    destinatario: "Juan Rodríguez",
    mascota: "Milo",
    tipo: "Recordatorio turno",
    fechaProgramada: "2024-01-15",
    estado: "Programado",
    mensaje: "Hola, te recordamos que mañana tenés turno con Milo a las 11:30 en Agroveterinaria Gross para control de otitis.",
  },
  {
    id: 3,
    destinatario: "Carlos López",
    mascota: "Simón",
    tipo: "Confirmación turno",
    fechaProgramada: "2024-01-14",
    estado: "Enviado",
    mensaje: "Hola, te confirmamos el turno de Simón para mañana a las 12:00 en Agroveterinaria Gross.",
  },
]

export const respuestasWhatsAppPendientes = [
  {
    id: 1,
    cliente: "Carlos López",
    mascota: "Simón",
    tipo: "Confirmación turno",
    mensaje: "Perfecto, confirmo el turno de mañana. Gracias!",
    fecha: "2024-01-14",
    hora: "18:45",
    requiereAccion: true,
  },
  {
    id: 2,
    cliente: "Ana Martínez",
    mascota: "Rocky",
    tipo: "Consulta indicaciones",
    mensaje: "Hola, Rocky sigue rascándose mucho. ¿Puede ser alergia? ¿Le doy algo?",
    fecha: "2024-01-14",
    hora: "20:30",
    requiereAccion: true,
  },
  {
    id: 3,
    cliente: "María García",
    mascota: "Luna",
    tipo: "Agradecimiento",
    mensaje: "Muchas gracias por la atención! Luna está mucho mejor.",
    fecha: "2024-01-13",
    hora: "16:20",
    requiereAccion: false,
  },
]

export const alertasClinicas = [
  {
    id: 1,
    tipo: "Crítica",
    mascota: "Simón",
    mensaje: "Control ERC urgente - creatinina elevada en último análisis",
    fecha: "2024-01-12",
  },
  {
    id: 2,
    tipo: "Importante",
    mascota: "Rocky",
    mensaje: "Vacuna antirrábica vencida hace 10 días",
    fecha: "2024-01-15",
  },
  {
    id: 3,
    tipo: "Moderada",
    mascota: "Max",
    mensaje: "Cirugía programada - verificar estudios prequirúrgicos",
    fecha: "2024-01-15",
  },
]

export const actividadReciente = [
  {
    id: 1,
    tipo: "consulta",
    descripcion: "Consulta finalizada - Luna",
    usuario: "Dr. García",
    hora: "09:45",
  },
  {
    id: 2,
    tipo: "vacuna",
    descripcion: "Vacuna registrada - Nina (Triple felina)",
    usuario: "Dra. López",
    hora: "09:30",
  },
  {
    id: 3,
    tipo: "turno",
    descripcion: "Turno confirmado - Simón (12:00)",
    usuario: "Recepción",
    hora: "09:15",
  },
  {
    id: 4,
    tipo: "estudio",
    descripcion: "Resultado cargado - Luna (Ecografía)",
    usuario: "Dra. López",
    hora: "09:00",
  },
  {
    id: 5,
    tipo: "whatsapp",
    descripcion: "Recordatorio enviado - Milo",
    usuario: "Sistema",
    hora: "08:30",
  },
]

export const historialLuna = [
  {
    id: 1,
    fecha: "2024-01-10",
    tipo: "Consulta",
    veterinario: "Dr. García",
    motivo: "Control postratamiento",
    sintomas: "Ninguno",
    diagnostico: "Evolución favorable",
    tratamiento: "Continuar con dieta especial",
    peso: "28.5",
    observaciones: "Paciente en excelente estado",
    proximoControl: "2024-02-10",
  },
  {
    id: 2,
    fecha: "2023-12-15",
    tipo: "Estudio",
    veterinario: "Dra. López",
    motivo: "Ecografía abdominal",
    sintomas: "-",
    diagnostico: "Sin hallazgos significativos",
    tratamiento: "-",
    peso: "28.2",
    observaciones: "Hígado, bazo, riñones sin alteraciones",
    archivo: "ecografia_luna_151223.pdf",
  },
  {
    id: 3,
    fecha: "2023-11-20",
    tipo: "Vacuna",
    veterinario: "Dr. García",
    motivo: "Vacunación anual",
    vacuna: "Séxtuple",
    lote: "AB12345",
    laboratorio: "Nobivac",
    proximaVacuna: "2024-11-20",
  },
  {
    id: 4,
    fecha: "2023-10-05",
    tipo: "Consulta",
    veterinario: "Dr. García",
    motivo: "Vómitos y diarrea",
    sintomas: "Vómitos 3 veces, diarrea acuosa, decaimiento",
    diagnostico: "Gastroenteritis aguda",
    tratamiento: "Metoclopramida, probióticos, dieta blanda",
    medicacion: [
      { nombre: "Metoclopramida", dosis: "0.5mg/kg", frecuencia: "Cada 8hs", duracion: "5 días" },
      { nombre: "Probióticos", dosis: "1 sobre", frecuencia: "Cada 12hs", duracion: "7 días" },
    ],
    peso: "27.8",
    observaciones: "Control en 48hs si no mejora",
    proximoControl: "2023-10-07",
  },
  {
    id: 5,
    fecha: "2023-06-15",
    tipo: "Cirugía",
    veterinario: "Dr. García",
    procedimiento: "Ovariohisterectomía",
    anestesia: "Propofol + Isoflurano",
    duracion: "45 minutos",
    complicaciones: "Ninguna",
    postoperatorio: "Collar isabelino 10 días, reposo, analgésicos",
  },
]

export const tareasInternas = [
  {
    id: 1,
    titulo: "Llamar a Carlos López",
    descripcion: "Confirmar si recibió resultados de Simón",
    responsable: "Recepción",
    prioridad: "Alta",
    fechaLimite: "2024-01-15",
    estado: "Pendiente",
  },
  {
    id: 2,
    titulo: "Cargar historia clínica - Rocky",
    descripcion: "Completar registro de consulta dermatológica",
    responsable: "Dr. García",
    prioridad: "Media",
    fechaLimite: "2024-01-15",
    estado: "Pendiente",
  },
  {
    id: 3,
    titulo: "Preparar certificado de salud - Nina",
    descripcion: "Certificado para viaje",
    responsable: "Dra. López",
    prioridad: "Alta",
    fechaLimite: "2024-01-16",
    estado: "En progreso",
  },
  {
    id: 4,
    titulo: "Enviar resultado de estudio",
    descripcion: "Enviar ecografía de Luna a María García",
    responsable: "Recepción",
    prioridad: "Media",
    fechaLimite: "2024-01-15",
    estado: "Completada",
  },
]

export const casosEnSeguimiento = [
  {
    id: 1,
    mascota: "Simón",
    mascotaId: 2,
    dueno: "Carlos López",
    condicion: "Enfermedad renal crónica - Estadío 2",
    tratamientoActivo: "Dieta renal, Fortekor",
    ultimoControl: "2024-01-12",
    proximoControl: "2024-01-26",
    notas: "Monitorear creatinina cada 2 semanas",
  },
  {
    id: 2,
    mascota: "Milo",
    mascotaId: 4,
    dueno: "Juan Rodríguez",
    condicion: "Otitis externa recurrente",
    tratamientoActivo: "Gotas óticas Otomax",
    ultimoControl: "2024-01-08",
    proximoControl: "2024-01-18",
    notas: "Evaluar respuesta al tratamiento",
  },
  {
    id: 3,
    mascota: "Max",
    mascotaId: 6,
    dueno: "Laura Fernández",
    condicion: "Tumor cutáneo - Pre cirugía",
    tratamientoActivo: "Ninguno",
    ultimoControl: "2024-01-11",
    proximoControl: "2024-01-18",
    notas: "Cirugía programada 18/01",
  },
]

export const tratamientosActivos = [
  {
    id: 1,
    mascota: "Simón",
    mascotaId: 2,
    diagnostico: "Enfermedad renal crónica",
    medicamento: "Fortekor 2.5mg",
    dosis: "1 comprimido",
    frecuencia: "Cada 24hs",
    duracion: "Indefinido",
    indicaciones: "Administrar en ayunas",
    fechaInicio: "2023-10-15",
    fechaFinalizacion: null,
    proximoControl: "2024-01-26",
    estado: "Activo",
  },
  {
    id: 2,
    mascota: "Milo",
    mascotaId: 4,
    diagnostico: "Otitis externa",
    medicamento: "Otomax gotas",
    dosis: "5 gotas cada oído",
    frecuencia: "Cada 12hs",
    duracion: "10 días",
    indicaciones: "Limpiar antes de aplicar",
    fechaInicio: "2024-01-08",
    fechaFinalizacion: "2024-01-18",
    proximoControl: "2024-01-18",
    estado: "Activo",
  },
  {
    id: 3,
    mascota: "Luna",
    mascotaId: 1,
    diagnostico: "Displasia de cadera",
    medicamento: "Condroprotector",
    dosis: "1 comprimido",
    frecuencia: "Cada 24hs",
    duracion: "3 meses",
    indicaciones: "Con comida",
    fechaInicio: "2023-12-01",
    fechaFinalizacion: "2024-03-01",
    proximoControl: "2024-02-10",
    estado: "Activo",
  },
]

export const vacunasRegistradas = [
  {
    id: 1,
    mascota: "Luna",
    mascotaId: 1,
    vacuna: "Séxtuple",
    fechaAplicada: "2023-11-20",
    proximaFecha: "2024-11-20",
    veterinario: "Dr. García",
    lote: "AB12345",
    laboratorio: "Nobivac",
    estado: "Aplicada",
  },
  {
    id: 2,
    mascota: "Luna",
    mascotaId: 1,
    vacuna: "Antirrábica",
    fechaAplicada: "2023-11-20",
    proximaFecha: "2024-11-20",
    veterinario: "Dr. García",
    lote: "CD67890",
    laboratorio: "Defensor",
    estado: "Aplicada",
  },
  {
    id: 3,
    mascota: "Rocky",
    mascotaId: 3,
    vacuna: "Antirrábica",
    fechaAplicada: "2023-01-05",
    proximaFecha: "2024-01-05",
    veterinario: "Dra. López",
    lote: "EF11223",
    laboratorio: "Defensor",
    estado: "Vencida",
  },
  {
    id: 4,
    mascota: "Simón",
    mascotaId: 2,
    vacuna: "Triple felina",
    fechaAplicada: "2023-08-22",
    proximaFecha: "2024-08-22",
    veterinario: "Dra. López",
    lote: "GH44556",
    laboratorio: "Felocell",
    estado: "Aplicada",
  },
  {
    id: 5,
    mascota: "Nina",
    mascotaId: 5,
    vacuna: "Triple felina",
    fechaAplicada: "2024-01-05",
    proximaFecha: "2025-01-05",
    veterinario: "Dra. López",
    lote: "IJ77889",
    laboratorio: "Felocell",
    estado: "Aplicada",
  },
]

export type EstadoVacunaClinica = "Aplicada" | "Próxima" | "Pendiente" | "Vencida"

export const vacunasClinicas = [
  {
    id: "vc-1",
    mascota: "Luna",
    mascotaId: 1,
    dueno: "María García",
    vacuna: "Antirrábica",
    estado: "Aplicada" as EstadoVacunaClinica,
    fechaAplicada: "2026-03-12",
    proximaFecha: "2027-03-12",
    fechaRecomendada: "2027-03-12",
    veterinario: "Dr. García",
    observaciones: "Aplicación anual registrada sin reacciones adversas.",
    recordatorioProgramado: true,
    proximoRecordatorio: "2027-03-05",
    mensajePreview: "Hola, te recordamos que a Luna le corresponde la vacuna Antirrábica el día 12/03/2027. Si querés, podés responder este mensaje para coordinar un turno en Agroveterinaria Gross.",
  },
  {
    id: "vc-2",
    mascota: "Luna",
    mascotaId: 1,
    dueno: "María García",
    vacuna: "Quíntuple",
    estado: "Aplicada" as EstadoVacunaClinica,
    fechaAplicada: "2026-02-20",
    proximaFecha: "2027-02-20",
    fechaRecomendada: "2027-02-20",
    veterinario: "Dr. García",
    observaciones: "Refuerzo anual completo.",
    recordatorioProgramado: true,
    proximoRecordatorio: "2027-02-13",
    mensajePreview: "Hola, te recordamos que a Luna le corresponde la vacuna Quíntuple el día 20/02/2027. Si querés, podés responder este mensaje para coordinar un turno en Agroveterinaria Gross.",
  },
  {
    id: "vc-3",
    mascota: "Luna",
    mascotaId: 1,
    dueno: "María García",
    vacuna: "Desparasitación",
    estado: "Aplicada" as EstadoVacunaClinica,
    fechaAplicada: "2026-04-05",
    proximaFecha: "2026-07-05",
    fechaRecomendada: "2026-07-05",
    veterinario: "Dra. López",
    observaciones: "Control trimestral recomendado por peso y rutina.",
    recordatorioProgramado: false,
    proximoRecordatorio: "2026-06-28",
    mensajePreview: "Hola, te recordamos que a Luna le corresponde la desparasitación el día 05/07/2026. Si querés, podés responder este mensaje para coordinar un turno en Agroveterinaria Gross.",
  },
  {
    id: "vc-4",
    mascota: "Luna",
    mascotaId: 1,
    dueno: "María García",
    vacuna: "Bordetella",
    estado: "Próxima" as EstadoVacunaClinica,
    fechaAplicada: null,
    proximaFecha: "2026-06-15",
    fechaRecomendada: "2026-06-15",
    veterinario: "Dra. López",
    observaciones: "Recomendada por exposición a guardería y paseos grupales.",
    recordatorioProgramado: true,
    proximoRecordatorio: "2026-06-10",
    mensajePreview: "Hola, te recordamos que a Luna le corresponde la vacuna Bordetella el día 15/06/2026. Si querés, podés responder este mensaje para coordinar un turno en Agroveterinaria Gross.",
  },
  {
    id: "vc-5",
    mascota: "Luna",
    mascotaId: 1,
    dueno: "María García",
    vacuna: "Refuerzo anual",
    estado: "Pendiente" as EstadoVacunaClinica,
    fechaAplicada: null,
    proximaFecha: "2027-02-20",
    fechaRecomendada: "2027-02-20",
    veterinario: null,
    observaciones: "Pendiente de confirmar agenda con la familia.",
    recordatorioProgramado: false,
    proximoRecordatorio: "2027-02-13",
    mensajePreview: "Hola, te recordamos que a Luna le corresponde el refuerzo anual el día 20/02/2027. Si querés, podés responder este mensaje para coordinar un turno en Agroveterinaria Gross.",
  },
  {
    id: "vc-6",
    mascota: "Luna",
    mascotaId: 1,
    dueno: "María García",
    vacuna: "Giardia",
    estado: "Vencida" as EstadoVacunaClinica,
    fechaAplicada: null,
    proximaFecha: "2026-05-10",
    fechaRecomendada: "2026-05-10",
    veterinario: null,
    observaciones: "Debe contactarse al dueño para coordinar aplicación.",
    recordatorioProgramado: false,
    proximoRecordatorio: "2026-05-27",
    mensajePreview: "Hola, te recordamos que a Luna le corresponde la vacuna Giardia desde el día 10/05/2026. Si querés, podés responder este mensaje para coordinar un turno en Agroveterinaria Gross.",
  },
  {
    id: "vc-7",
    mascota: "Rocky",
    mascotaId: 3,
    dueno: "Ana Martínez",
    vacuna: "Antirrábica",
    estado: "Vencida" as EstadoVacunaClinica,
    fechaAplicada: "2025-01-05",
    proximaFecha: "2026-01-05",
    fechaRecomendada: "2026-01-05",
    veterinario: "Dra. López",
    observaciones: "Paciente con vacuna anual vencida. Priorizar contacto.",
    recordatorioProgramado: true,
    proximoRecordatorio: "2026-05-28",
    mensajePreview: "Hola, te recordamos que a Rocky le corresponde la vacuna Antirrábica desde el día 05/01/2026. Si querés, podés responder este mensaje para coordinar un turno en Agroveterinaria Gross.",
  },
  {
    id: "vc-8",
    mascota: "Rocky",
    mascotaId: 3,
    dueno: "Ana Martínez",
    vacuna: "Bordetella",
    estado: "Próxima" as EstadoVacunaClinica,
    fechaAplicada: null,
    proximaFecha: "2026-06-20",
    fechaRecomendada: "2026-06-20",
    veterinario: "Dr. García",
    observaciones: "Sugerida para reducir riesgo respiratorio.",
    recordatorioProgramado: false,
    proximoRecordatorio: "2026-06-15",
    mensajePreview: "Hola, te recordamos que a Rocky le corresponde la vacuna Bordetella el día 20/06/2026. Si querés, podés responder este mensaje para coordinar un turno en Agroveterinaria Gross.",
  },
  {
    id: "vc-9",
    mascota: "Simón",
    mascotaId: 2,
    dueno: "Carlos López",
    vacuna: "Triple felina",
    estado: "Aplicada" as EstadoVacunaClinica,
    fechaAplicada: "2026-03-02",
    proximaFecha: "2027-03-02",
    fechaRecomendada: "2027-03-02",
    veterinario: "Dra. López",
    observaciones: "Aplicación anual felina.",
    recordatorioProgramado: true,
    proximoRecordatorio: "2027-02-23",
    mensajePreview: "Hola, te recordamos que a Simón le corresponde la vacuna Triple felina el día 02/03/2027. Si querés, podés responder este mensaje para coordinar un turno en Agroveterinaria Gross.",
  },
  {
    id: "vc-10",
    mascota: "Milo",
    mascotaId: 4,
    dueno: "Juan Rodríguez",
    vacuna: "Séxtuple",
    estado: "Próxima" as EstadoVacunaClinica,
    fechaAplicada: null,
    proximaFecha: "2026-06-08",
    fechaRecomendada: "2026-06-08",
    veterinario: "Dr. García",
    observaciones: "Aprovechar próximo control de otitis.",
    recordatorioProgramado: false,
    proximoRecordatorio: "2026-06-03",
    mensajePreview: "Hola, te recordamos que a Milo le corresponde la vacuna Séxtuple el día 08/06/2026. Si querés, podés responder este mensaje para coordinar un turno en Agroveterinaria Gross.",
  },
]

export const estudiosArchivos = [
  {
    id: 1,
    mascota: "Luna",
    mascotaId: 1,
    tipo: "Ecografía",
    descripcion: "Ecografía abdominal completa",
    fecha: "2023-12-15",
    profesional: "Dra. López",
    estado: "Archivado en historial",
    archivo: "ecografia_luna_151223.pdf",
  },
  {
    id: 2,
    mascota: "Simón",
    mascotaId: 2,
    tipo: "Análisis de sangre",
    descripcion: "Perfil renal completo",
    fecha: "2024-01-12",
    profesional: "Dra. López",
    estado: "Pendiente de resultado",
    archivo: null,
  },
  {
    id: 3,
    mascota: "Max",
    mascotaId: 6,
    tipo: "Radiografía",
    descripcion: "Radiografía de tórax prequirúrgica",
    fecha: "2024-01-11",
    profesional: "Dr. García",
    estado: "Resultado recibido",
    archivo: "rx_torax_max_110124.jpg",
  },
  {
    id: 4,
    mascota: "Rocky",
    mascotaId: 3,
    tipo: "Foto clínica",
    descripcion: "Lesión dermatológica flanco izquierdo",
    fecha: "2023-12-05",
    profesional: "Dr. García",
    estado: "Archivado en historial",
    archivo: "foto_rocky_dermatitis.jpg",
  },
]

export const cirugias = [
  {
    id: 1,
    mascota: "Max",
    mascotaId: 6,
    dueno: "Laura Fernández",
    tipo: "Extirpación tumor cutáneo",
    fecha: "2024-01-18",
    hora: "10:00",
    veterinario: "Dr. García",
    ayudante: "Dra. López",
    estado: "Programada",
    prequirurgico: {
      pesoActual: "35.0",
      edad: "6 años",
      estadoGeneral: "Bueno",
      antecedentes: "Artrosis lumbar",
      alergias: "Ninguna conocida",
      enfermedadesPrevias: "Artrosis",
      medicacionActual: "Condroprotector",
      estudiosSolicitados: ["Análisis de sangre", "Radiografía de tórax", "ECG"],
      riesgoQuirurgico: "Moderado",
      observaciones: "Vigilar función cardíaca durante anestesia",
    },
    consentimiento: {
      firmado: true,
      fechaFirma: "2024-01-11",
      archivo: "consentimiento_max_cirugía.pdf",
      responsable: "Recepción",
    },
    registroCirugia: null,
    anestesia: null,
    postoperatorio: null,
  },
  {
    id: 2,
    mascota: "Rocky",
    mascotaId: 3,
    dueno: "Ana Martínez",
    tipo: "Castración",
    fecha: "2024-01-22",
    hora: "09:00",
    veterinario: "Dra. López",
    ayudante: null,
    estado: "Pendiente confirmación",
    prequirurgico: null,
    consentimiento: {
      firmado: false,
      fechaFirma: null,
      archivo: null,
      responsable: null,
    },
    registroCirugia: null,
    anestesia: null,
    postoperatorio: null,
  },
  {
    id: 3,
    mascota: "Luna",
    mascotaId: 1,
    dueno: "María García",
    tipo: "Ovariohisterectomía",
    fecha: "2023-06-15",
    hora: "10:00",
    veterinario: "Dr. García",
    ayudante: "Dra. López",
    estado: "Realizada",
    prequirurgico: {
      pesoActual: "26.5",
      edad: "2 años",
      estadoGeneral: "Excelente",
      antecedentes: "Ninguno",
      alergias: "Pollo",
      enfermedadesPrevias: "Ninguna",
      medicacionActual: "Ninguna",
      estudiosSolicitados: ["Análisis de sangre"],
      riesgoQuirurgico: "Bajo",
      observaciones: "",
    },
    consentimiento: {
      firmado: true,
      fechaFirma: "2023-06-14",
      archivo: "consentimiento_luna_cirugia.pdf",
      responsable: "Recepción",
    },
    registroCirugia: {
      fechaRealizacion: "2023-06-15",
      horaInicio: "10:00",
      horaFinalizacion: "10:45",
      procedimiento: "Ovariohisterectomía por línea media",
      veterinario: "Dr. García",
      ayudantes: ["Dra. López"],
      diagnosticoPrevio: "Paciente sano - cirugía electiva",
      hallazgos: "Útero y ovarios sin alteraciones",
      complicaciones: "Ninguna",
      observaciones: "Procedimiento sin incidentes",
    },
    anestesia: {
      tipo: "General inhalatoria",
      medicacion: ["Propofol", "Isoflurano"],
      dosis: "Propofol 4mg/kg IV, Isoflurano 1.5-2%",
      via: "IV + Inhalatoria",
      reaccion: "Normal",
      complicaciones: "Ninguna",
      observaciones: "Recuperación anestésica sin incidentes",
    },
    postoperatorio: {
      medicacion: ["Meloxicam 0.1mg/kg", "Amoxicilina-Clavulánico 12.5mg/kg"],
      dosis: "Meloxicam 1 vez/día, Antibiótico cada 12hs",
      frecuencia: "5 días analgésico, 7 días antibiótico",
      cuidadosEnCasa: "Reposo absoluto, evitar escaleras, no mojar herida",
      reposoRecomendado: "10 días",
      collarIsabelino: true,
      signosAlerta: "Sangrado, secreción, fiebre, decaimiento excesivo",
      fechaControl: "2023-06-20",
      retiroPuntos: "2023-06-25",
      observacionesDueno: "Administrar medicación con comida",
    },
  },
]

export const profesionales = [
  {
    id: 1,
    nombre: "Dr. García",
    especialidad: "Clínica general y cirugía",
    rol: "Veterinario",
    email: "garcia@agroveterinariagross.com",
  },
  {
    id: 2,
    nombre: "Dra. López",
    especialidad: "Medicina interna y diagnóstico por imágenes",
    rol: "Veterinario",
    email: "lopez@agroveterinariagross.com",
  },
  {
    id: 3,
    nombre: "María Rodríguez",
    especialidad: "Atención al cliente",
    rol: "Recepción",
    email: "recepcion@agroveterinariagross.com",
  },
]

export const configuracion = {
  veterinaria: {
    nombre: "Agroveterinaria Gross",
    direccion: "Av. Principal 1234, Ciudad",
    telefono: "(376) 444 5555",
    email: "info@agroveterinariagross.com",
    horarios: "Lunes a Viernes 9:00-19:00, Sábados 9:00-13:00",
  },
  tiposVacunas: [
    "Antirrábica",
    "Séxtuple",
    "Quíntuple",
    "Triple felina",
    "Leucemia felina",
    "Tos de las perreras",
    "Giardia",
  ],
  tiposEstudios: [
    "Análisis de sangre",
    "Ecografía",
    "Radiografía",
    "Electrocardiograma",
    "Foto clínica",
    "Receta",
    "Certificado",
    "Informe PDF",
  ],
  tiposCirugia: [
    "Castración",
    "Ovariohisterectomía",
    "Extracción dental",
    "Limpieza dental",
    "Cirugía de herida",
    "Extirpación de tumor",
    "Cesárea",
    "Cirugía traumatológica",
    "Cirugía menor",
  ],
}
